version: "3.5"
services:
  mall-nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: mall-nacos
    ports:
      - 8848:8848
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    networks:
      - mall


  mall-mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: mall-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    security_opt:
      - seccomp:unconfined
    networks:
      - mall

  mall-redis:
    platform: linux/x86_64 # fix M1 bug
    image: redis:6.2.6
    container_name: mall-redis
    ports:
      - 6379:6379
    networks:
      - mall

  mall-es:
    build:
      context: ./es
    image: elasticsearch:7.12.1
    container_name: mall-es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    networks:
      - mall
    restart: always

  mall-kibana:
    image: kibana:7.12.1
    container_name: mall-kibana
    links:
      - mall-es
    depends_on:
      - mall-es
    networks:
      - mall
    ports:
      - 5601:5601
#    volumes:
#      - ./es/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://mall-es:9200
    restart: always

networks:
  mall:
    name: mall
    driver: bridge



