server:
  port: 9991
  servlet:
    # 接口访问路径限定
    context-path: /buyer

# 配置不需要登录就可以访问的url
ignored:
  urls:
    - /pages/**
    - /pageData/**
    - /article/**
    - /goods/**
    - /members/**
    - /category/**
    - /common/**

spring:
  application:
    name: mall-buyer
  profiles:
    # 本机开发环境
    active: local


